# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Welcome to STaRS!
email: adolocmihu@ggc.edu
author: STaRS IT subcommittee 
copyright: Copyright © 2021
description: >- # this means to ignore newlines until "baseurl:"
  Georgia Gwinnett College yearly event Science Technology and Reseach Symposium (STaRS)
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.html
  - about.md

#   - archives.html
#   - categories.html
#   - tags.html

# Page default value
defaults:
  home:
    heading: "STaRS 2021 is on April 8, noon-3pm"
    subheading: "Welcome to the Science Technology and Reseach Symposium (STaRS) organized by the School of Science and Technology at Georgia Gwinnett College"
    banner: "/assets/images/sst-image-fb.jpg"

# Build settings
markdown: kramdown
#theme: minima
# theme: owner/name --> Don't forget to remove/comment the gem-based theme option
remote_theme: "jeffreytse/jekyll-theme-yat"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
