# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Welcome to STaRS 2022 @ GGC!
email: adolocmihu@ggc.edu
author: STaRS IT subcommittee
copyright: Copyright © 2022
description: >- # this means to ignore newlines until "baseurl:"
  Georgia Gwinnett College yearly event Science Technology and Reseach Symposium (STaRS)
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.html
  - about.md
  - schedule.md
#  - posters.md
  - archives.md
   #- activities.md
  #- sponpors.md
  #- gradschools.md
  #- tshirtcontest.md
#  - merchandise.md


#   - categories.html
#   - tags.html

# Page default value
defaults:
  home:
      heading: "STaRS 2022 is on April 14th, 10am-3pm"
      subheading: "Welcome to the Science Technology and Research Symposium (STaRS) organized by the School of Science and Technology at Georgia Gwinnett College"
      banner: "/assets/images/stars-logo-green-right.png"

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is"manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
#
night_mode: "manual"

# Page generation from posters
page_gen-dirs: false

page_gen:
  - data: stars2021.posters
    template: 'poster'
    dir: '/stars2021/posters'
    index_files: false
    name: "group"
    title: "group"
    debug: false

subject_emojis:
    Information Technology: IT 💾
    Biology: Biology 🧬
    Chemistry: Chemistry 🧪
    Exercise Science: Exercise Science 💪
    Environmental Science: Environmental Science 🌎
    Physics: Physics 💥
    Mathematics: Mathematics Σ
    Regents Engineering Pathway: "Regents' Engineering Pathway 🔧"
    1st_place: 1st PLACE 🥇
    2nd_place: 2nd PLACE 🥈
    3rd_place: 3rd PLACE 🥉
    Honorable Mention: Honorable Mention 🏅

# Build settings
markdown: kramdown
#theme: minima
# theme: owner/name --> Don't forget to remove/comment the gem-based theme option
remote_theme: "jeffreytse/jekyll-theme-yat"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-datapage-generator

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
