name: Build and Deploy GIT Update
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          export PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
          gem install --user-install jekyll -v 3.9.0
          gem install --user-install bundler 
          bundle install
          bundle exec jekyll build --trace -V

      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          ref: gh-pages-stars2021
          path: _site/stars2021

      - name: Remove git
        run: rm -rf _site/stars2021/.git

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
