name: Build and Deploy GIT Update
on: [push]
jobs:
  build-and-deploy:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      # Use GitHub Actions' cache to cache dependencies on servers
      - name: Cache 🤑
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Build only 🔧 
        uses: actions/jekyll-build-pages@v1 # Use official action

      - name: Checkout 2021 archive branch 🛎️
        uses: actions/checkout@v3
        with:
          ref: gh-pages-stars2021
          path: _site/archive-stars2021

      - name: Remove archive git repo ❌
        run: rm -rf _site/archive-stars2021/.git

      - name: Upload site ↗️
        uses: actions/upload-pages-artifact@v1 # official action in beta
          
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v1
      
      #- name: Deploy 🚀
      #  uses: JamesIves/github-pages-deploy-action@4.1.0
      #  with:
      #    branch: gh-pages # The branch the action should deploy to.
      #    folder: _site # The folder the action should deploy.
